export const ROUTES = {
  dashboard: "/dashboard",
  productManagement: "/dashboard/product-management",
  sales: "/dashboard/sales",
  inventory: "/dashboard/inventory",
  category: "/dashboard/categories",
  returns: "/dashboard/returns",
  customer: "/dashboard/customer",
  happyTime: "/dashboard/happy-time",
  transaction: "/dashboard/transaction",
  stores: "/dashboard/stores",
  report: "/dashboard/reports",
  createOrder: "/dashboard/sales/create_order",
  viewOrder: "/dashboard/sales/view_order",
  test: "/dashboard/#",
};
