export enum OrderCreationStep {
  SEARCH_PRODUCT = "SEARCH_PRODUCT",
  CONFIRM_PAYMENT = "CONFIRM_PAYMENT",
  CUSTOMER_RECEIPT = "CUSTOMER_RECEIPT",
}

export enum ProductManagementStep {
  BASIC_INFORMATION = "SEARCH_PRODUCT",
  PRICING_INFORMATION = "CONFIRM_PAYMENT",
  PRODUCT_VARIATIONS = "CUSTOMER_RECEIPT",
  PROMOTIONS = "PROMOTIONS",
  ADDITIONAL_INFORMATION = "ADDINTIONAL_INFORMATION",
  COMPLIANCE_INFORMATION = "COMPLIANCE_INFORMATION",
}

export interface OrderCreationContextType {
  currentStep: OrderCreationStep;
  nextStep: () => void;
  prevStep: () => void;
}
